import numpy as np
import torch
import numpy as np
import requests
import random
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch.nn.functional as F
from fastapi import FastAPI
import yaml


# --------------------------------------------------------------------------
# Load system configuration
# --------------------------------------------------------------------------
with open("config.yaml", "r") as f:
    CONFIG = yaml.safe_load(f)

API_BASE_KNOWLEDGE = CONFIG["api"]["knowledge"]
API_BASE_TIMING = CONFIG["api"]["timing"]

MODEL = CONFIG["generation_model"]["name"]
filename = CONFIG["generation_model"]["gguf_file"]
device = CONFIG["generation_model"]["device"]

MAX_TOKEN = CONFIG["generation_model"]["max_token"]

app = FastAPI()

# --------------------------------------------------------------------------
# Initialize the Primary Reasoning Model.
#
# The model is loaded in GGUF format using Hugging Face Transformers.
# --------------------------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL, gguf_file=filename)
model = AutoModelForCausalLM.from_pretrained(
    MODEL, gguf_file=filename,
    dtype=torch.float32,
    attn_implementation="eager",
)

model.to(device)
model.eval()  

def fetch_knowledge(question):
    """
    Initiate asynchronous knowledge retrieval.

    This function sends the user's question to the Knowledge Service, which
    begins retrieving relevant external information in the background.
    Generation continues immediately without waiting for retrieval to finish.

    Parameters
    ----------
    question : str
        User input question.

    Returns
    -------
    str
        Unique identifier used to poll the Knowledge Service for completion.
    """
    url = f"{API_BASE_KNOWLEDGE}/fetch-knowledge"
    response = requests.post(url, json={"question": question})
    if response.status_code == 200:
        return response.json()["id"]
    else:
        raise Exception(f"Failed to start fetch: {response.text}")

def check_knowledge_ready(knowledge_id):
    """
    Check whether asynchronous knowledge retrieval has completed.

    When retrieval is complete, the returned knowledge dictionary is converted
    into a formatted text block that can later be appended directly to the
    model context for knowledge injection.

    Parameters
    ----------
    knowledge_id : str
        Identifier returned by fetch_knowledge().

    Returns
    -------
    tuple(bool, Optional[str])

        (False, None)
            Retrieval is still running.

        (True, knowledge_text)
            Retrieval completed successfully.
    """
    url = f"{API_BASE_KNOWLEDGE}/check-knowledge"
    response = requests.get(url, params={"id": knowledge_id})
    
    if response.status_code != 200:
        raise Exception(f"Status check failed: {response.text}")
    
    data = response.json()
    status = data.get("status")

    if status == "ready":
        knowledge_dict = data.get("knowledge", {})
        # Convert the dict into a readable string
        if len(knowledge_dict) == 0:
            return True, ""
        knowledge_text = "Trust following Knowledge:\n"
        knowledge_text += "\n".join(
            f"{topic}: {description}" for topic, description in knowledge_dict.items()
        )
        return True, knowledge_text
    elif status == "error":
        raise Exception(f"Knowledge fetch error: {data.get('error')}")
    else:
        return False, None
    
def check_good_timing(question, output, attention):
    """
    Query the IPM Service to determine whether the current
    reasoning state is suitable for knowledge injection.

    The timing model receives the original question, the partially generated
    reasoning, and summarized attention statistics to predict whether external
    knowledge can be injected without disrupting the model's reasoning process.

    Parameters
    ----------
    question : str
        Original user question.

    output : str
        Current partial response generated by the reasoning model.

    attention : list
        Aggregated attention statistics extracted from generated paragraphs.

    Returns
    -------
    str
        "True" if knowledge should be injected at the current step;
        otherwise "False".
    """
    r = requests.post(F"{API_BASE_TIMING}/timing", json={"question": question, "output": output, "attention": attention})
    r.raise_for_status()
    data = r.json()
    return data.get("timing", "")

def stopper(input_ids, logits):
    return input_ids[-1] == model.token_eos()

def generate_one_paragraph(model, input_ids, max_tokens=300):
    """
    Generate a single paragraph of reasoning while collecting attention data.

    Parameters
    ----------
    model
        Primary Reasoning Model.

    input_ids : Tensor
        Current prompt including previously generated text.

    max_tokens : int
        Maximum number of tokens allowed for this paragraph.

    Returns
    -------
    tuple

        generated_text : str
            Newly generated paragraph.

        finished : bool
            Whether generation naturally terminated.

        token_count : int
            Number of generated tokens.

        input_ids : Tensor
            Updated input sequence.

        avg_attn : Tensor
            Mean attention over attention heads in the paragraph.
    """
    generated_text = ""
    token_count = 0
    finished = True

    all_attns = []

    for _ in range(max_tokens):
        with torch.no_grad():
            outputs = model.generate(
                input_ids=input_ids,
                attention_mask=torch.ones_like(input_ids),
                max_new_tokens=1,
                do_sample=False,
                output_attentions=True,
                return_dict_in_generate=True,
            )

        # get the newly generated token
        new_token_id = outputs.sequences[:, -1:]
        token_count += 1

        # decode only the new token
        new_text = tokenizer.decode(
            new_token_id[0],
            skip_special_tokens=True
        )

        generated_text += new_text
        input_ids = torch.cat([input_ids, new_token_id], dim=1)

        # collect last-layer attention for this step
        step_attn = outputs.attentions[0][-1][0, :, -1, :].detach().cpu()  # (batch, heads, seq_len, seq_len)
        all_attns.append(step_attn)

        # Treat a blank line as the end of the current reasoning step
        if generated_text.endswith("\n\n"):
            finished = False
            break

    if token_count >= max_tokens:
        finished = False

    # ---- Attention aggregation ----
    last_layer_attns = all_attns

    max_len = max(a.shape[-1] for a in last_layer_attns)
    padded = []

    for a in last_layer_attns:
        pad_len = max_len - a.shape[-1]
        if pad_len > 0:
            a = F.pad(a, (0, pad_len))
        padded.append(a)

    attn = torch.stack(padded, dim=0)
    avg_attn = attn.mean(dim=1)

    return generated_text.strip(), finished, token_count, input_ids, avg_attn


def interactive_answer_generation(
    question,
    model,
    max_paragraphs=35,
    verbose=False,
    smart=True,
):
    """
    Execute the complete HASKI inference pipeline.

    The function coordinates three independent components:

    1. Primary Reasoning Model
       Generates the response incrementally.

    2. Knowledge Service
       Retrieves external knowledge asynchronously in parallel with
       generation.

    3. IPM
       Determines the optimal point for knowledge injection based on
       the current reasoning state and attention statistics.

    Knowledge retrieval latency is hidden by allowing the reasoning model
    to continue generating while retrieval executes in the background.
    Once knowledge becomes available, it is injected only when the Timing
    Prediction Service predicts minimal disruption to the reasoning process.

    Parameters
    ----------
    question : str
        User question.

    model
        Primary Reasoning Model.

    max_paragraphs : int
        Maximum number of paragraph-generation iterations before
        terminating.

    verbose : bool
        Print intermediate generation results.

    smart : bool
        Enable timing-aware knowledge injection. When False, knowledge
        is injected immediately after retrieval.

    Returns
    -------
    str
        Final response generated by the HASKI framework.
    """
    id = fetch_knowledge(question)

    input_text = f'''{question}''' + "\n\n<think>\n"

    # encode question into context
    input_ids = tokenizer.encode(input_text, return_tensors="pt").to(device)

    total_token = input_ids.shape[1]

    checkpoints = [0, total_token]

    partial_output = ""
    knowledge_used = False
    i = 0
    finished = False
    good_timing = False

    last_token_attention = None

    ready = False
    knowledge_text = ""
    new_paragraph = ""
    while i < max_paragraphs:
        # Poll the Knowledge Service without interrupting ongoing generation.
        # If retrieval is still in progress, continue reasoning normally.
        if not ready:
            ready, knowledge_text = check_knowledge_ready(id)

        if ready and not knowledge_used and smart and len(checkpoints) > 2:
            if finished:
                good_timing = True
            else:
                summed = []
                for i in range(len(checkpoints)-2):
                    summed.append(last_token_attention[:, checkpoints[i]:checkpoints[i+1]].sum(dim=0).sum(dim=0).tolist())

                good_timing = check_good_timing(question, partial_output, summed) == "True"

        # Inject retrieved knowledge once it is available and either:
        #   (1) the Timing Prediction Service approves the current reasoning state,
        #   or
        #   (2) smart timing is disabled.
        if (ready and not knowledge_used) and (good_timing or not smart):
            knowledge = knowledge_text.strip()
            knowledge = "\n\n" + knowledge + "\n\n"

            if knowledge.strip() != "":
                partial_output += knowledge

                new_tokens = tokenizer.encode(knowledge, return_tensors="pt").to(device)
                input_ids = torch.cat([input_ids, new_tokens], dim=1)

                total_token += new_tokens.shape[1]

                if verbose:
                    print(knowledge, end="")

            knowledge_used = True
            finished = False

        # Continue incremental reasoning until either knowledge is injected
        # or the reasoning process naturally reaches completion.
        if not finished:
            if not knowledge_used:
                new_paragraph, finished, token_count, input_ids, last_token_attention = \
                generate_one_paragraph(
                    model,
                    input_ids,
                    max_tokens=min(MAX_TOKEN - total_token, 200),
                )
        
                i += 1
                total_token += token_count
                partial_output += "\n\n" + new_paragraph

                if verbose:
                    print(new_paragraph, end="")

                checkpoints.append(total_token)
                if "</think>" in new_paragraph and not finished and not knowledge_used:
                    knowledge_used = True             
            else:
                with torch.no_grad():
                    outputs = model.generate(
                        input_ids=input_ids,
                        attention_mask=torch.ones_like(input_ids),
                        max_new_tokens=max(1, MAX_TOKEN - total_token),
                        return_dict_in_generate=True,
                        do_sample=False,
                    )

                new_token_id = outputs.sequences[:, input_ids.shape[1]:]
                total_token += new_token_id.shape[1]

                # decode *only* the new token
                new_text = tokenizer.decode(
                    new_token_id[0],
                    skip_special_tokens=True
                )

                partial_output += "\n\n" + new_text   
                finished = True 

                if verbose:
                    print(new_text)

        if total_token >= MAX_TOKEN:
            break

        # Terminate once the response has completed after knowledge injection,
        # or when the maximum token budget has been exhausted.
        if finished and knowledge_used:
            break


    return partial_output.strip()

# --------------------------------------------------------------------------
# Endpoints
# --------------------------------------------------------------------------

@app.get("/HASKI_generate")
def HASKI_generate(question,
    max_paragraphs=35,
    verbose=False,
    smart=True,):
    response = interactive_answer_generation(question,
    model,                                      
    max_paragraphs,
    verbose,
    smart)

    return response